language: python

python:
 - 2.7

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.7
      - python3.5

env:
 - TOXENV=py27
 - TOXENV=py35

before_install:
 - sudo apt-get install python3-gi

install:
 - if [[ $(echo "$TOXENV" | egrep -c "(py2[45]|py31)") != 0 ]]; then pip install virtualenv==1.7.2 tox==1.3; fi;
 - if [[ $(echo "$TOXENV" | egrep -c "(py2[45]|py31)") == 0 ]]; then pip install tox; fi;

script:
 - tox

notifications:
  email:
    - shubhodeep9@gmail.com
